name: Test Actions Runner
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building..." && sleep 10

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - run: echo "deploying..."
